pipeline:

  restore_cache:
    image: appleboy/drone-sftp-cache
    restore: true
    mount: [ .glide, vendor ]
    ignore_branch: true

  build:
    image: appleboy/golang-testing:${GO_VERSION}
    environment:
      - GOPATH=/go
    commands:
      - make install
      - coverage all

  rebuild_cache:
    image: appleboy/drone-sftp-cache
    rebuild: true
    mount: [ .glide, vendor ]
    ignore_branch: true
    when:
      branch: master

workspace:
  path: /go/src/github.com/appleboy/gin-jwt

matrix:
  GO_VERSION:
    - 1.6.3
    - 1.7.1
