sudo: false

language: go

services:
  - docker

go:
  - 1.6.x
  - 1.7.x
  - tip

before_install:
  - curl https://glide.sh/get | sh

install:
  - make install

script:
  - go test -v -cover -coverprofile=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.txt
